# -*- coding: utf-8 -*-
"""automacao-mkt-chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ntH0UcxJLgm3dovfZ2YjoSwSGPjcqM8g
"""

import pandas as pd
import datetime

url = "https://raw.githubusercontent.com/Russel-Servicos/automacao-mkt-chat/main/Exemplo_Planilha_Chat.csv?token=GHSAT0AAAAAACT5WJTE6YRAG5Q63NMGKT5AZWYLI7A"
url = "./planilha_chat_estagio_1_exemplo.csv"
df = pd.read_csv(url)

data = "04/09/2024"

# Remove linhas duplicadas
df = df.drop_duplicates(subset=["Name"])

# Remove colunas
df = df.drop(columns=['Visitor ID', 'Initiated Time', 'IP', 'Mode'], axis=1)

# Renomeia colunas
columns = {
    "Name": "ID do Visitante",
    "Page": "Página de Aterrissagem",
    "Campaign Medium": "Meio",
    "Campaign Name": "Campanha",
    "Campaign Source": "Origem",
    "State": "Estado",
    "Source": "Canal"
}
df = df.rename(columns=columns)

# Cria novas colunas
df['Data'] = data
df['Qualificação'] = ''
df['Contagem'] = ''
df['Taxa de Conversão'] = ''

# Reorganiza colunas
df = df.reindex(['Data', 'ID do Visitante', 'Canal', 'Página de Aterrissagem', 'Question', 'Origem',
                'Meio', 'Campanha', 'Estado', 'Keyword', 'Qualificação', 'Contagem', 'Taxa de Conversão'], axis=1)
df.head()

# Atribui as linhas, o valor "Emprego"
query_is_emprego = "(Question in 'Quero Emprego') or (Question in 'Busco Emprego')"
df_is_emprego = df.query(query_is_emprego)
df_is_emprego.loc[:, "Qualificação"] = "Emprego"

query_is_not_emprego = "(Question not in 'Quero Emprego') and (Question not in 'Busco Emprego')"
df_not_is_emprego = df.query(query_is_not_emprego)

df = pd.concat([df_is_emprego, df_not_is_emprego])

# Cria linha vazia embaixo da linha das colunas
df.loc[-1] = [data, "", "", "", "", "",
              "", "", "", "", "", "", ""]
df.index = df.index + 1
df = df.sort_index()

# Exportar como CSV
now = datetime.datetime.now()
now = now.strftime("%Y_%m_%d_%H_%M")
df.to_csv(f'./planilha_chat_estagio_1de2_{now}.csv', index=False)
